[platformio]
default_envs = esp32-c3

[env:esp32-c3]
platform = espressif32@^6.10.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  adafruit/Adafruit SHT31 Library@^2.2.2
  adafruit/ENS160 - Adafruit Fork@^3.0.1
  adafruit/Adafruit SSD1306@^2.5.13
  adafruit/Adafruit GFX Library@^1.12.1
  adafruit/Adafruit NeoPixel@^1.15.1
  tzapu/WiFiManager@^2.0.17
  bblanchon/ArduinoJson@^6.21.5
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_CDC_ON_BOOT=0
  -include Arduino.h

[env:native]
platform = native
test_framework = unity
test_build_src = no
